#!/bin/sh

set -e

echo ""
echo "  RecordRecon"
echo ""

# Check if Bundler is present
if test ! $(which bundler); then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
else
  echo "  + Bundler found."
fi

echo "  + Installing dependencies..."
bundle install --quiet

rake db:create
rake db:migrate
rake db:test:prepare

echo ""
echo "  We're ready to rock!"
